# Generated by Django 5.0.4 on 2024-04-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_attempt_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Актиность'),
        ),
    ]
