# Generated by Django 5.0.4 on 2024-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='last_try',
            field=models.DateTimeField(verbose_name='Дата и время попытки'),
        ),
    ]
